(setq scheme-path "C:\\Program Files\\Chez Scheme 9.5.8\\bin\\ta6nt")
(setq clangd-path "C:\\LLVM\\bin\\clangd.exe")
(setq sbcl-path "C:\\opt\\sbcl\\sbcl.exe")
(setq python-path "C:\\Python\\python39\\python.exe")
(setq pandoc-path "C:\\Pandoc\\pandoc.exe")
